# Generated by Django 3.1.7 on 2021-04-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status_code', models.IntegerField()),
                ('status_message', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('rank_group', models.IntegerField()),
                ('rank_absolute', models.IntegerField()),
                ('domain', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('breadcrumb', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=50)),
                ('se', models.CharField(max_length=50)),
                ('se_type', models.CharField(max_length=50)),
                ('language_code', models.CharField(max_length=50)),
                ('location_code', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=200)),
                ('device', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='tasks.task')),
            ],
        ),
    ]
