# Generated by Django 3.1.7 on 2021-04-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='breadcrumb',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
